### PR TITLE
Redirect page with minimum UI style

### PR DESCRIPTION
**Pull request by ReinforceZwei**
Auth code:
image

Error:
image

@ORelio would you like to select a background picture of your favorite for the redirect page?

### CODE REVIEW

**Comment by ORelio** [comment]
I'm not sure what we could use, maybe some nice Minecraft wallpaper 🤔
We could make a Windows Spotlight-like rolling wallpaper 🤣

**Comment by ReinforceZwei** [comment]
> We could make a Windows Spotlight-like rolling wallpaper 🤣

Sure! Just need to collect some nice pictures.

**Comment by ORelio** [comment]
Here are a few landscape pictures I took a long while ago:

**Comment by ReinforceZwei** [comment]
I am negotiating with the owner of the Minecraft server `mcFallout.net` for some awesome building photos to be used as background pictures. They are happy to let us use them but require us to add declaration for the use of the photo. @ORelio do you agree we use their photos?

**Comment by ORelio** [comment]
I was thinking you could put a box like in Windows Spotlight that could countain some info like Title, Author and some copyright text. If by "declaration" you mean "give credit", of course I agree with that :)

**Pull request merged**
